name: webview_flutter_wkwebview_extend
description: A Flutter plugin that extends official webview_flutter_wkwebview plugin.
repository: https://github.com/Heewookji/plugins/tree/main/packages/webview_flutter/webview_flutter_wkwebview
version: 0.0.1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: webview_flutter
    platforms:
      ios:
        pluginClass: FLTWebViewFlutterPlugin

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  webview_flutter_platform_interface: 0.0.1

dev_dependencies:
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  pedantic: ^1.10.0
  pigeon: ^2.0.3
