name: webview_flutter_android_extend
description: A Flutter plugin that extends official webview_flutter_android plugin.
repository: https://github.com/Heewookji/plugins/tree/main/packages/webview_flutter/webview_flutter_android
version: 0.0.1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: webview_flutter
    platforms:
      android:
        package: io.flutter.plugins.webviewflutter
        pluginClass: WebViewFlutterPlugin

dependencies:
  flutter:
    sdk: flutter
  webview_flutter_platform_interface: 0.0.1

dev_dependencies:
  build_runner: ^2.1.4
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  pedantic: ^1.10.0
  pigeon: 1.0.9
