name: webview_flutter_extend
description: A Flutter plugin that extends official webview_flutter plugin.
repository: https://github.com/Heewookji/plugins/tree/main/packages/webview_flutter/webview_flutter
version: 0.0.1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: webview_flutter_android
      ios:
        default_package: webview_flutter_wkwebview

dependencies:
  flutter:
    sdk: flutter
  webview_flutter_android_extend: 0.0.1
  webview_flutter_platform_interface_extend: 0.0.1
  webview_flutter_wkwebview_extend: 0.0.1

dev_dependencies:
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  pedantic: ^1.10.0
